<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Classified;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;


/**
 * ClassifiedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassifiedRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param Classified $classified Classified entity
     * @param User       $user    User entity
     */
    public function save(Classified $classified, $user = null)
    {
        $classified->setUser($user);
        $this->_em->persist($classified);
        $this->_em->flush();
    }


    /**
     * Delete entity.
     *
     * @param Classified $classified Classified entity
     */
    public function delete(Classified $classified)
    {
        $this->_em->remove($classified);
        $this->_em->flush();
    }

    /**
     * Query all entities.
     *
     * @param User $user User entity
     *
     * @return \Doctrine\ORM\Query
     */
    public function findAllCLassified($user)
    {
        return $this->_em->createQuery('
            SELECT a
            FROM AppBundle:Classified a
            WHERE a.user = :user
            ORDER BY a.id DESC
        ')->setParameter('user', $user)->getResult();
    }

    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     * @param string|null $string Search query
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1, $string = null)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll($string), false));
        $paginator->setMaxPerPage(Classified::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * Gets all records paginated.
     *
     * @param Tag $tag Tag entity
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginatedByTag($tag, $page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAllByTag($tag), false));
        $paginator->setMaxPerPage(Classified::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }


    /**
     * Query all entities.
     *
     * @param string|null $string Search query
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAll($string = null)
    {
        if ($string) {
            return $this->_em->createQuery('
                SELECT a
                FROM AppBundle:Classified a
                WHERE a.name LIKE :string
                ORDER BY a.id DESC
            ')->setParameter('string', '%' . $string . '%');
        }

        return $this->_em->createQuery('
            SELECT a
            FROM AppBundle:Classified a
            ORDER BY a.id DESC
        ');
    }

    /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAllByTag($tag)
    {
        return $this->_em->createQuery('
            SELECT a
            FROM AppBundle:Classified a
            WHERE a.tag = :tag
            ORDER BY a.id DESC
        ')->setParameter('tag', $tag);
    }

}