<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use AppBundle\Entity\Publisher;

/**
 * PublisherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublisherRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param Publisher $publisher Publisher entity
     */
    public function save(Publisher $publisher)
    {
        $this->_em->persist($publisher);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Publisher $publisher Publisher entity
     */
    public function delete(Publisher $publisher)
    {
        $this->_em->remove($publisher);
        $this->_em->flush();
    }

    /**
     * Gets all records paginated.
     *
     * @param int         $page   Page number
     * @param string|null $string Search query
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1, $string = null)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll($string), false));
        $paginator->setMaxPerPage(Publisher::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * Query all entities.
     *
     * @param int $maxResults maximum result
     *
     * @return \Doctrine\ORM\Query
     */
    public function getLastAdded($maxResults)
    {
        return $this->_em->createQuery('
            SELECT a
            FROM AppBundle:Publisher a
            ORDER BY a.id DESC
        ')->setMaxResults($maxResults)->getResult();
    }

    /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAll($string = null)
    {
        if ($string) {
            return $this->_em->createQuery('
                SELECT a
                FROM AppBundle:Publisher a
                WHERE a.name LIKE :string
                ORDER BY a.id ASC
            ')->setParameter('string', '%'.$string.'%');
        }

        return $this->_em->createQuery('
            SELECT a
            FROM AppBundle:Publisher a
            ORDER BY a.name ASC
        ');
    }
}